config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "properties#index"

  resources :properties, only: [:index, :show, :create, :new, :edit, :update, :destroy]

  resources :users, only:[:index]

  resources :homepage, only: [:index]

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_many :notes

    validates :address, presence: true
    validates :unit_id, presence: true
    validates :rent_amount, presence: true
    validates :number_of_rooms, presence: true
    validates :pet_friendly,inclusion: { in: [true, false] }
    validates :occupied_or_not, inclusion: { in: [true, false] }
    validates :rent_deposit, presence: true
    validates :begining_of_lease_date, presence: true
    validates :end_of_lease_date,presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private
  def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
  end


  def new
    @property = Property.new
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      flash[:success] = 'Property saved successfully'
      redirect_to property_path(@property)
    else
      flash[:alert] = 'Problems updating property'
      @errors = @property.errors.full_messages
      render :edit
    end
  end

  def destroy
    @property = property.find(params[:id])
    if @property.destroy
      flash[:success] = 'Property deleted successfully'
      redirect_to property_path
    else
      flash[:alert] = 'Problems deleting property'
      redirect_to property_path(@property)
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def create
    @property = Property.new(property_params)

  if @property.save
    flash[:notice] = "Property added successfully"
    redirect_to @property
  else
    flash[:errors] = @property.errors.full_messages.join(", ")
    render :new

  end
end

  private

  def property_params
    params.require(:property).permit(:address, :unit_id, :rent_amount, :number_of_rooms, :pet_friendly, :occupied_or_not, :rent_deposit, :begining_of_lease_date, :end_of_lease_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= image_tag "" %>

<head>
  <title>PropertyManager20</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>


<body>
  <div class="top-bar">
     <div class="top-bar-left">
       <ul class="menu">
         <li class="menu-text">Property Manager 2.0</li>
         <li><a href="#">About</a></li>
       </ul>
     </div>

     <div class="top-bar-right">
       <ul class="menu">
         <li><a href="/users/sign_up">Sign up</a></li>
         <li><a href="/users/sign_in">Sign In</a></li>
         <li><a href="/properties">Main Page</a></li>
         <li><%= button_to "Sign out", destroy_user_session_path,class: "signout", method: :delete %></li>
       </ul>
     </div>
   </div>

   <% flash.each do |type, message| %>
     <div class="flash flash-<%= type %>">
       <%= message %>
     </div>
   <% end %>


<%= yield %>

<!-- <script src="app/assets/javascripts/jquery.js"></script>
   <script src="app/asets/javascripts/what-input.min.js"></script>
   <script src="app/assets/javascripts/foundation.min.js"></script>
   <script>
     $(document).foundation();
   </script> -->
</body>
</html>

app/views/partial/_partial.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="medium-4 medium-centered">
    <h6><%= @property.address %></h6>

    <%= form_for @property do |f| %>
    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :unit_id %>
    <%= f.text_field :unit_id %>

    <%= f.label :rent_amount %>
    <%= f.text_field :rent_amount %>

    <%= f.label :number_of_rooms %>
    <%= f.text_field :number_of_rooms %>

    <%= f.label :pet_friendly %>
    <%= f.text_field :pet_friendly %>

    <%= f.label :occupied_or_not %>
    <%= f.text_field :occupied_or_not %>

    <%= f.label :rent_deposit %>
    <%= f.text_field :rent_deposit %>

    <%= f.label :begining_of_lease_date %>
    <%= f.text_field :begining_of_lease_date %>

    <%= f.label :end_of_lease_date%>
    <%= f.text_field :end_of_lease_date %>


    <%= f.submit "Add Property" %>

    <% end %>

app/views/properties/index.html.erb
<div>
  <ul>
  <% @properties.each do |property| %>
    <li><%= link_to property.address, property_path(property) %></li>
    <%= link_to  'EDIT', edit_property_path(property), class: 'button' %>
  <% end %>
  </ul>
  <%= link_to 'New property Form', new_property_path, class: 'button'  %>
</div>

app/views/properties/new.html.erb
<div class="medium-4 medium-centered">
    <h6>New property Form</h6>

    <%= form_for @property do |f| %>
    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :unit_id %>
    <%= f.text_field :unit_id %>

    <%= f.label :rent_amount %>
    <%= f.text_field :rent_amount %>

    <%= f.label :number_of_rooms %>
    <%= f.text_field :number_of_rooms %>

    <%= f.label :pet_friendly %>
    <%= f.text_field :pet_friendly %>

    <%= f.label :occupied_or_not %>
    <%= f.text_field :occupied_or_not %>

    <%= f.label :rent_deposit %>
    <%= f.text_field :rent_deposit %>

    <%= f.label :begining_of_lease_date %>
    <%= f.text_field :begining_of_lease_date %>

    <%= f.label :end_of_lease_date%>
    <%= f.text_field :end_of_lease_date %>


    <%= f.submit "Add Property" %>

    <% end %>

app/views/properties/show.html.erb
<div>
    <ul><%= @property.address %></ul>
    <ul><%= @property.unit_id %></ul>
    <ul><%= @property.rent_amount %></ul>
    <ul><%= @property.number_of_rooms %></ul>
    <ul><%= @property.pet_friendly %></ul>
    <ul><%= @property.occupied_or_not %></ul>
    <ul><%= @property.rent_deposit %></ul>
    <ul><%= @property.begining_of_lease_date %></ul>
    <ul><%= @property.end_of_lease_date %></ul>
</div>
show page

app/views/user/index.html.erb
<%= render "devise/registration/new" %>